Modernize and release
CINPLA/head-direction pull request #2
Opened 2024-11-28 10:56 UTC by alejoe91

@lepmik @nicolossus same as spatial map :)

@lepmik can you add the `PYPI_API_TOKEN` here as well?

2024-11-28 11:07 UTC, nicolossus requested changes

2024-11-28 11:07 UTC, nicolossus commented on pyproject.toml
> +description = "Compute spatial maps for neural data."
```suggestion
description = "Analysis of head direction cells."
```

2024-11-28 11:07 UTC, nicolossus commented on .pre-commit-config.yaml
> +      - id: black-jupyter
```suggestion
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
      - id: black-jupyter
```

The excludes are not needed here.

2024-11-28 11:07 UTC, nicolossus commented on pyproject.toml
> +    "numpy<2",
Won't this quickly create a conflict since many packages now are based on numpy>=2?

2024-11-28 11:14 UTC, alejoe91 commented on pyproject.toml
> +    "numpy<2",
I think several packages are still lagging behind due to updates on the numba side (e.g. SpikeInterface)

2024-11-28 11:17 UTC, nicolossus approved these changes

2024-11-28 12:37 UTC, merged

2024-11-29 12:33 UTC, lepmik commented
api token done